# ========================================
# PREPROD PROFILE
# ========================================

aws:
  secrets:
    enabled: true
    secret-ids: ${AWS_SECRETS_SECRET_IDS}
    fail-fast: true

security:
  https: true

logging:
  level:
    root: INFO
    com.srrfrr.api: INFO
    org.hibernate.SQL: WARN
    org.springframework.web: WARN
    liquibase: WARN
