# Database principale
spring.datasource.url=${DATA_SOURCE_URL:jdbc:postgresql://localhost:5432/srrfrrdb}
spring.datasource.username=${DATA_SOURCE_USERNAME:db_admin}
spring.datasource.password=${DATA_SOURCE_PASSWORD:123}

# Hibernate / JPA
spring.jpa.properties.hibernate.default_schema=${HIBERNATE_DEFAULT_SCHEMA:app_mobile}
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=${HIBERNATE_SHOW_SQL:false}

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=public
spring.liquibase.liquibase-schema=public
spring.liquibase.user=${LIQUIBASE_USERNAME:liquibase_user}
spring.liquibase.password=${LIQUIBASE_PASSWORD:123}

# Archive schema
archive.schema=${ARCHIVE_SCHEMA:archive}

spring.profiles.active=${SPRING_PROFILE_ACTIVE:test}
whatsapp.api.token=${WHATSAPP_API_TOKEN:xxxxxxxxxxxxxxxxxxxx}
whatsapp.phone.id=${BUSINESS_PHONE_NUMBER_ID:xxxxxxxxxxxxxxxxxxxx}
whatsapp.template=${WHATSAPP_TEMPLATE_NAME:xxxxxxxxxxxxxxxxxxxx}

google.api.key=${GOOGLE_API_KEY:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}

jwt.secret=${JWT_SECRET_KEY:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
jwt.internal=${JWT_INTERNAL_KEY:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}

spring.security.user.name=${SPRING_SECURITY_USER_NAME:xxxxxxxxxxxxxxxxxxxx}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:xxxxxxxxxxxxxxxxxxxx}

data.bucket.name=${DATA_BUCKET_NAME:xxxxxxxxxxx}
aws.region=${AWS_REGION:xxxxxxxxxxxxxx}
aws.accessKeyId=${aws_access_key_id:xxxxxxxxxxxxxx}
aws.secretAccessKey=${aws_secret_access_key:xxxxxxxxxxxxxx}
aws.sessionToken=${aws_session_token:xxxxxxxxxxxxxx}

# CloudFront
cloudfront.domain=${CLOUDFRONT_DOMAIN:xxxxxxxxxxxxxx}
cloudfront.distribution.id=${CLOUDFRONT_DISTRIBUTION_ID:xxxxxxxxxxxxxxxxxxxxxxxxxxx}
cloudfront.privateKeyPath=${CLOUDFRONT_PRIVATE_KEY_PATH:xxxxxxxxxxxxxxxxxxxxxxx}
cloudfront.keyPairId=${CLOUDFRONT_KEY_PAIR_ID:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}

wallet.initial.balance=${WALLET_INITIAL_BALANCE:480.0}
#spring.redis.host=${SPRING_REDIS_HOST:redis}
#spring.redis.port=${SPRING_REDIS_PORT:6379}

#SPRING_REDIS_HOST=redis
#SPRING_REDIS_PORT=6379